[package]
name = "wormhole"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
bytemuck = { version = "1.25.2", features = ["derive"] }
gltf = { version = "1.4.1", features = ["KHR_materials_emissive_strength"] }
image = { version = "0.24", default-features = false, features = ["png", "gif", "jpeg"] }
nalgebra = "0.35.0"
pollster = "1.0.1"
wgpu = "30.0.0"
winit = "0.30.13"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
